### ISSUE TITLE
Detection results on whole test set

### ISSUE THREAD

**Issue by JingweiJ** [vkalogeiton/joint-object-action-learning#1]
Hi,

Thanks for releasing the codes of this great work! While I'm trying to run the evaluation pipeline, I found that not all detection results are released to reproduce Table 4 by running `vic_A2D_eval`. Could you release all detection results on test set so that the pipeline of evaluation could be run?

Thanks again!

**Comment by vkalogeiton** [comment]
Hey,

It's done!
