### ISSUE TITLE
Scripts for test on objects and actions separately

### ISSUE THREAD

**Issue by JingweiJ** [vkalogeiton/joint-object-action-learning#3]
Hi,

Thanks a lot for releasing the codes and follow up for this great work! I notice there is only eval script for test on objects+actions, but the scripts for test on objects and actions separately are not released. It would be appreciated if codes to generate numbers in the first two columns in Table 4 are also added.

Thanks again!

**Comment by JingweiJ** [comment]
Hi, just to check in if there is any chance to have these released (to ensure consistent benchmarking for object and action separately). Thank you again and really appreciate it :)

**Comment by vkalogeiton** [comment]
Thank you for your interest. I updated the code. Please let me know if there is anything else that you may need.
