### ISSUE TITLE
Error running vic_A2D_eval.m --> detections\-4KMQsUaSAQ\00056_multitask.mat'. No such file or directory.

### ISSUE THREAD

**Issue by jgallegov** [vkalogeiton/joint-object-action-learning#4]
Hello,

I am trying to check your proposal, but I came accross one error:

Error using load
detections\-4KMQsUaSAQ\00056_multitask.mat'. No such
file or directory.

Error in vic_compute_multitaskBoxes (line 54)
    det = load([paths.test_detections GT_List{ii} '_' options.learning_case '.mat']);

Error in vic_A2D_eval (line 44)
[det_obj_boxes, det_act_boxes, det_obj_act_boxes] = ComputeBoxesFunction(gt_test.images, paths, options);

Can you please tell me if smth is missing?

Thx

**Comment by jgallegov** [comment]
Ok, solved by installing JointLearningDetections.tar.gz downloded from:

http://pascal.inrialpes.fr/data2/joint-objects-actions/

**Comment by jgallegov** [comment]
I have another issue: 

Undefined function or variable 'computeOverlapTableDouble'.

Error in vic_map_objects_actions (line 40)
      ov = computeOverlapTableDouble(double(currBoxes(:,1:4)), currentGT);

Error in vic_A2D_eval (line 60)
                [res] = vic_map_objects_actions(gt_test, C, det_obj_act_boxes, V);

Please, can you explain how to solve it? The code present several other errors that I achieved to solve, but this one, I have no idea.

**Comment by vkalogeiton** [comment]
Hello,

Thank you for the interest in our work. 
I did not upload the computeOverlapTableDouble source code but I will create an alternative function that can work on windows. 
In the meantime, could you please let me know what are the other several errors that you encountered? 

Thanks a lot.

**Comment by jgallegov** [comment]
Hello,
thank you for your response. I wait for the file. I hope you will be able to upload it in the following days.

About the errors I found trying to use vic_A2D_eval(learning_case):


Error using load
Unable to read file 'pwd/detections/-4KMQsUaSAQ/00028_multitask.mat'. No such file or directory.

Error in vic_compute_multitaskBoxes (line 54)
    det = load([paths.test_detections GT_List{ii} '_' options.learning_case '.mat']);

Error in vic_A2D_eval (line 44)
[det_obj_boxes, det_act_boxes, det_obj_act_boxes] = ComputeBoxesFunction(gt_test.images, paths, options);

--> Solved in vic_A2D_eval changing: load(['pwd' '/src/gt_test_A2D.mat'],'gt_test') by load([pwd '/src/gt_test_A2D.mat'],'gt_test')

I hope this will help to improve the code. Thank you!

**Comment by vkalogeiton** [comment]
Hi,

Thank you for the pwd error. I updated it. 
I also created another function for computing the overlap between boxes. 
Please try to run the evaluation again and let me know if you have any problems. 

Thank you again for the interest.
