### ISSUE TITLE
 computeOverlapTableDouble.mexa64 compiled for windows?

### ISSUE THREAD

**Issue by jgallegov** [vkalogeiton/joint-object-action-learning#5]
I have another issue on windows:

_Undefined function or variable 'computeOverlapTableDouble'.

Error in vic_map_objects_actions (line 40)
      ov = computeOverlapTableDouble(double(currBoxes(:,1:4)), currentGT);

Error in vic_A2D_eval (line 60)
                [res] = vic_map_objects_actions(gt_test, C, det_obj_act_boxes, V);_

Please, can you provide the computeOverlapTableDouble.mexa64 compiled for windows? or even the computeOverlapTableDouble.cc to compile it by ourselves?

Thank you!

**Comment by vkalogeiton** [comment]
Hello,

Thank you for the interest. 
Please look at the issue: https://github.com/vkalogeiton/joint-object-action-learning/issues/4
