### ISSUE TITLE
undefined function or variable 'computeOverlapTableDouble'

### ISSUE THREAD

**Issue by sander-ali** [vkalogeiton/joint-object-action-learning#6]
Hello there,
Actually I have checked previous issues and you told that you have added this file but yet I am getting this error while running the vic_A2D_eval(1) command. 

I am using MATLAB2017a on windows10, Although I see a file in utils folder but MATLAB is unable to recognize the file as function

**Comment by vkalogeiton** [comment]
Dear sander-ali,

Thank you for the interest in our work. 
Could you please tell me what is the error?

**Comment by sander-ali** [comment]
Thank you for replying vicky,

The error is undefined function or variable 'computeOverlapTableDouble'.

Although a mex file exists in utils but the code is unable to read the
function. I checked with visual studio 2015 and microsoft sdk as mex
compilers. The code returns the same error

Regards,

**Comment by vkalogeiton** [comment]
Dear sander-ali,

Thank you for the message. You didn't mention in which line you have the error but I think I managed to reproduce it. Now it should be fixed.
