### ISSUE TITLE
How to train the proposed network with actor-action dataset?

### ISSUE THREAD

**Issue by jianhua2022** [vkalogeiton/joint-object-action-learning#7]
As far as I know, the actor-action dataset is sparsely annotate with bounding boxes and pixel-wise masks over 3-5 frames for each video, while your proposed model seems to train with actor-action dataset frame by frame, and video by video.  So my question is how to train your proposed model with sparse annotation dataset? I will be appreciated for your reply, thank you very much! 

Jayson

**Comment by vkalogeiton** [comment]
Hi Jayson, 
Thank you for the interest. For training, we used only the frames with ground truth annotations. We computed the optical flow between each annotated frame and its following (in time) one and assigned it to the annotated frame. 
I hope this helps.
